pipeline {
    agent any
    
    stages {
         stage('Checkout') {
            steps {
            checkout([$class: 'GitSCM', branches: [[name: '*/main']], extensions: [], userRemoteConfigs: [[url: 'https://github.com/Bohdan-Kobliuk/test.git']]])        

          }
        }
         
        stage('Plan') {
            steps {
                sh 'terraform init'
            }
        }
        

        
        stage('Apply') {
            steps {
                sh "terraform apply --auto-approve"
            }
        }
    }

   
}
