pipeline {
    agent any
    tools {
        terraform 'Terraform_1'
    }


    
    environment {
        AWS_ACCESS_KEY_ID     = credentials('AWS_ACCESS_KEY_ID')
        AWS_SECRET_ACCESS_KEY = credentials('AWS_SECRET_ACCESS_KEY')
    }

    stages {
         stage('Checkout') {
            steps {
            checkout([$class: 'GitSCM', branches: [[name: '*/main']], extensions: [], userRemoteConfigs: [[url: 'https://github.com/Bohdan-Kobliuk/test.git']]])        

          }
        }
         
        stage('Plan') {
            steps {
                bat 'terraform init'
            }
        }
        

        
        stage('Apply') {
            steps {
                bat "terraform apply --auto-approve"
            }
        }
    }

   
}
